A few fixes
steelbrain/pundle pull request #155
Opened 2017-07-12 05:20 UTC by natew

I need to fix this up, revert the `@mcro/` preset and maybe split it up. Just wanted to put this here.

Has three changes done in sloppy form as I'm not positive on how everything works yet.

1. After generating a full bundle, cache it and use cache if unchanged
2. After ticking for HMR, wait 2 seconds, then rebuild bundle
3. Don't give up on websockets reconnecting, even with network errors (I run into this one actually a few times every day)

2017-07-12 06:39 UTC, steelbrain commented
Can we use the babel-preset-env with stage zero instead?

2017-07-12 18:39 UTC, natew commented
Yep! Was planning on reverting that. I was seeing slow HMR last night
though so want to check this over.

On Tue, Jul 11, 2017 at 11:39 PM Steel Brain <notifications@github.com>
wrote:

> Can we use the babel-preset-env with stage zero instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/steelbrain/pundle/pull/155#issuecomment-314669095>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAvRLhrU4kasgWl_AkYJJ8PhVtGaa4tks5sNGosgaJpZM4OVI58>
> .
>

2017-07-13 07:56 UTC, steelbrain requested changes
Really nice work so far 👏 
Left a few comments

2017-07-13 07:56 UTC, steelbrain commented on packages/dev/src/browser/index.js
> +    console.log(`[HMR] Retrying in ${retryTime} seconds`)
retryTime is miliseconds here, you need to do /1000

2017-07-13 07:56 UTC, steelbrain commented on package.json
> +    "@mcro/preset-motion": "5.0.2",
Any ideas why this was reverted? Can you show me the error the other preset was causing?

2017-07-13 07:56 UTC, steelbrain commented on packages/dev/src/index.js
> +  async generateChunkForUrl(url: string): Promise<Object> {
How many different URLs are we expecting? IIRC we only have one bundlePath

2017-07-13 07:56 UTC, steelbrain commented on packages/dev/src/index.js
> +              this.state.hasChanged = true
Instead of `hasChanged` can we instead check with `this.state.changed.size`?

2017-07-13 07:56 UTC, steelbrain commented on packages/generator-default/rollup.config.js
> -import uglify from 'rollup-plugin-uglify'
I would be fine with removing this for development NODE_ENV but removing it entirely isn't what I want, it'll make the bundle output sizes really big

2017-07-13 07:56 UTC, steelbrain commented on packages/generator-default/wrappers/.babelrc
> -    "modules": false
Rollup stops working with the modules enabled, this should be reverted

2017-07-13 07:56 UTC, steelbrain commented on packages/motion/src/compilation.js
> +        require.resolve('pundle-plugin-commons-chunk'),
Can you re-add npm installer? It's working fine in latest version

2017-07-13 07:56 UTC, steelbrain commented on packages/dev/src/index.js
> +    this.enqueue(() =>
Can you please revert the style changes as they are out of scope of this PR?

2017-07-26 16:52 UTC, natew commented on package.json
> +    "@mcro/preset-motion": "5.0.2",
If you create a new app with motion and then change the babelrc to use @mcro/preset-motion, you'll see it won't boot up due to error where it's looking for `babel-preset-steelbrain`. I imagine this is the case for all other presets and is a bug somewhere. The solution is obviously not this, I was just pushing my local fix :/

2017-07-26 16:53 UTC, natew commented on packages/dev/src/index.js
> +  async generateChunkForUrl(url: string): Promise<Object> {
I thought for code-splitting perhaps.

2017-07-26 16:53 UTC, natew commented on packages/dev/src/index.js
> +              this.state.hasChanged = true
Yep, I believe I had tried that but it wasn't working for whatever reason. I can try again.

2017-07-26 17:02 UTC, closed without merging